export const FETCH_TRUMP_TWEETS = 'FETCH_TRUMP_TWEETS';
export const LATEST_TRUMP_TWEETS = 'LATEST_TRUMP_TWEETS';
export const FETCH_HILLARY_TWEETS = 'FETCH_HILLARY_TWEETS';
export const LATEST_HILLARY_TWEETS = 'LATEST_HILLARY_TWEETS';